version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - general-dependencies

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: general-dependencies

      - run: mvn clean package